version: "3.9"

services:
  photobooth:
    container_name: photobooth
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - BGREMOVER_API_BASE=${BGREMOVER_API_BASE:-http://bgremover:3000}
    ports:
      - "3001:3000"
    volumes:
      - ./storage:/app/storage
    networks:
      - apps-net
    restart: unless-stopped

networks:
  apps-net:
    external: true
